#  _    _ _    _  _____ 
# | |  | | |  | |/ ____|
# | |  | | |__| | |     
# | |  | |  __  | |     
# | |__| | |  | | |____ 
#  \____/|_|  |_|\_____|
# The most customisable UHC plugin for Minecraft PE !
---
name: UHC
author: Ad5001
description: (FIRST COMMIT) UHC Plugin created by Ad5001 brought back to life!
version: 1.0.1
api: [2.0.0, 3.0.0, 4.0.0, 3.9.3, 3.9.4, 3.9.5]
main: Ad5001\UHC\Main
commands: 
   uhc:
     description: Main UHC command
     usage: "/uhc <sub-command> [params]"
     permission: uhc.command.main
   scenarios:
     description: Manage UHC scenarios
     usage: "/scenarios [add | remove | list] [scenario]"
     permission: uhc.command.scenarios
     aliases: [scs]
permissions:
   uhc.command.main:
     default: true
   uhc.command.start&stop:
     default: op
   uhc.command.scenarios:
     default: true
   uhc.scenarios.modify:
     default: op
...
